### ISSUE TITLE
request database mysql

### ISSUE THREAD

**Issue by alanyukeroo** [fannyhasbi/perpustakaan#5]
mas klo boleh minta file databasenya sekalian ? biar langsung bisa dicoba, terimakasih

**Comment by fannyhasbi** [comment]
Mohon maaf, proyek ini sudah lama tidak saya kerjakan lagi. Kemungkinan database sudah tidak ada dan tergantikan dengan database yang baru.

**Comment by fannyhasbi** [comment]
Karena banyaknya permintaan file database, sehingga saya buat versi terbaru dari aplikasi ini dengan memanfaatkan beberapa logika dan fungsi dasar dari versi sebelumnya. Silahkan baca-baca pada commit/merge #9 

Setelah itu, kamu bisa lakukan beberapa hal untuk mendapatkan versi barunya
* git stash perubahan yang sudah kamu lakukan di repo local

  atau

* git clone dari awal
