### ISSUE TITLE
maaf mas, mau tanya, itu databasenya gmn ya? saya mau pelajari soalnya, terima kasih

### ISSUE THREAD

**Issue by icalo** [fannyhasbi/perpustakaan#6]

**Comment by fannyhasbi** [comment]
Sudah ditambahkan pada merge #9 dengan versi terbaru dari aplikasi ini. Silahkan baca perubahan apa saja yang ada di fitur terbaru.

Silahkan lakukan pull untuk mendapatkan databasenya

> Karena perubahan kode yang *massive* kemungkinan besar terjadinya conflict

Langkah yang bisa dilakukan antaranya:
* git stash perubahan yang sudah kamu lakukan di repo local
* git clone dari awal
